apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: sample-app-analysis
  namespace: sample-app
spec:
  metrics:
    - name: error-rate
      interval: 1m
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus.argo-rollouts.svc.cluster.local
          query: sum(rate(http_requests_total{status!~"2.."}[1m])) / sum(rate(http_requests_total[1m]))
    - name: latency
      interval: 1m
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus.argo-rollouts.svc.cluster.local
          query: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))
