apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-app
resources:
  - namespace.yaml
  - deployment.yaml
  - configmap.yaml
  - service.yaml
  - service-account.yaml
  - virtual-service.yaml

patches:
  - target:
      version: v1
      kind: ServiceAccount
      name: gke-workload-identity-ksa
      namespace: sample-app
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          iam.gke.io/gcp-service-account: gke-workload-identity-gsa@phx-01had7ny8p.iam.gserviceaccount.com